# NOTE: ONLY INSTALL DEPENDENCIES, you can add applications through cask as you need them

# Taps
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/cask"

# Binaries
brew "git"
brew "zsh"
brew "node"
brew "yarn"